version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - client
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
