import {
  GENRES_ENDPOINT,
  EVENT_ENDPOINT,
  AUTH_ENDPOINT,
  USER_ENDPOINT,
  RESERVATION_ENDPOINT,
} from "./endpoints.js";
export {
  GENRES_ENDPOINT,
  EVENT_ENDPOINT,
  AUTH_ENDPOINT,
  USER_ENDPOINT,
  RESERVATION_ENDPOINT,
};
